-- Database schema for SaloneVibe
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(255),
    role ENUM('user','artist','admin') NOT NULL DEFAULT 'user',
    profile_image_url VARCHAR(500),
    bio TEXT,
    location VARCHAR(255),
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS artists (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    stage_name VARCHAR(255),
    genre VARCHAR(100),
    city_or_region VARCHAR(150),
    country VARCHAR(150) NOT NULL DEFAULT 'Sierra Leone',
    bio TEXT,
    notable_songs TEXT,
    image_url VARCHAR(500),
    social_youtube VARCHAR(500),
    social_spotify VARCHAR(500),
    social_instagram VARCHAR(500),
    social_facebook VARCHAR(500),
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_artist_name (name),
    INDEX idx_artist_genre (genre),
    INDEX idx_artist_city (city_or_region)
);

CREATE TABLE IF NOT EXISTS favorites (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    artist_id INT NOT NULL,
    created_at DATETIME NOT NULL,
    UNIQUE KEY uniq_user_artist (user_id, artist_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (artist_id) REFERENCES artists(id) ON DELETE CASCADE
);

INSERT INTO artists (name, stage_name, genre, city_or_region, country, bio, notable_songs, image_url, social_youtube, social_spotify, social_instagram, social_facebook, created_at, updated_at) VALUES
('Amara Denis Turay', 'Kao Denero', 'Hip-Hop', 'Freetown', 'Sierra Leone', 'Legendary rapper known for sharp lyricism and advocacy for Sierra Leonean hip-hop.', '["King Boss","Green Gold","Sweet Salone"]', 'https://via.placeholder.com/300?text=Kao+Denero', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Emmerson Bockarie', 'Emmerson', 'Afrobeat', 'Bo', 'Sierra Leone', 'Afrobeat singer celebrated for socially conscious anthems that resonate nationwide.', '["Borbor Belleh","Tutu Party","Timin"]', 'https://via.placeholder.com/300?text=Emmerson', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Benjamin Menelik George', 'Drizilik', 'Afro-fusion', 'Freetown', 'Sierra Leone', 'Afro-fusion star blending krio rap with global sounds; a new-school favorite.', '["Shukubly","Move Right","Ashobi"]', 'https://via.placeholder.com/300?text=Drizilik', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Rosemarie Baryoh', 'Rozzy Sokota', 'Afropop', 'Freetown', 'Sierra Leone', 'Powerful vocalist with energetic Afropop hits and heartfelt ballads.', '["Sokota","For You","Aleh"]', 'https://via.placeholder.com/300?text=Rozzy', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Mohamed Saccoh', 'Markmuday', 'Afropop', 'Freetown', 'Sierra Leone', 'Hitmaker known for melodic hooks and club-ready Afropop bangers.', '["Kabba","Laka Lakata","Mumu"]', 'https://via.placeholder.com/300?text=Markmuday', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Zainab Sheriff', 'Star Zee', 'Dancehall', 'Freetown', 'Sierra Leone', 'Trailblazing dancehall queen with fierce delivery and stage presence.', '["Champion","Big Up","Colabo"]', 'https://via.placeholder.com/300?text=Star+Zee', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Alhaji Amadu Bah', 'Boss LA', 'Hip-Hop', 'Freetown', 'Sierra Leone', 'Influential rapper blending street narratives with patriotic themes.', '["Talk Talk","Money Na Bank","Thank God"]', 'https://via.placeholder.com/300?text=Boss+LA', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Abdul Sesay', 'YOK 7', 'Hip-Hop', 'Freetown', 'Sierra Leone', 'Veteran hip-hop voice with charismatic flows and uplifting hooks.', '["Champion","Na Me En You","Fine Baby"]', 'https://via.placeholder.com/300?text=YOK7', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Ibrahim Olamide Kargbo', 'Shadow Boxxer', 'Hip-Hop', 'Freetown', 'Sierra Leone', 'Punchline-heavy rapper respected for lyrical precision and storytelling.', '["Alpha & Omega","Dreams","Babylon"]', 'https://via.placeholder.com/300?text=Shadow+Boxxer', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Ishmael Koroma', 'Famous', 'Afro-fusion', 'Freetown', 'Sierra Leone', 'Vibrant Afro-fusion singer known for heartfelt hooks and feel-good vibes.', '["Yagba","Borbor Pain","Follow U"]', 'https://via.placeholder.com/300?text=Famous', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Abdul Aziz Kamara', 'Arkman', 'Afropop', 'Freetown', 'Sierra Leone', 'Smooth singer delivering catchy Afropop singles loved on radio.', '["Pretty Girl","Go Down","Kompin"]', 'https://via.placeholder.com/300?text=Arkman', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Kandeh Bangura', 'K-Man', 'Afropop', 'Makeni', 'Sierra Leone', 'Northern crooner blending Afropop with folk sensibilities.', '["Baby Na You","Freetown","Enjoy"]', 'https://via.placeholder.com/300?text=K-Man', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Mohamed Kamara', 'Nega Don', 'Dancehall', 'Freetown', 'Sierra Leone', 'High-energy dancehall artist with club anthems and street appeal.', '["Badman","Touch You","Control"]', 'https://via.placeholder.com/300?text=Nega+Don', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Edward Wright', 'Eddie 441', 'R&B', 'Freetown', 'Sierra Leone', 'Silky R&B vocalist from the iconic 441 collective.', '["Love You","Broke My Heart","Feel Right"]', 'https://via.placeholder.com/300?text=Eddie+441', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Alonzo Teah Abasi', 'Alonzo', 'R&B', 'Freetown', 'Sierra Leone', 'Liberia-born Sierra Leone-based singer known for soulful R&B crossovers.', '["Angel","Pray for Me","Freedom"]', 'https://via.placeholder.com/300?text=Alonzo', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Abizzy Kabba', 'Abizzy', 'Afropop', 'Freetown', 'Sierra Leone', 'International Afropop act merging Sierra Leonean melodies with global pop.', '["Sugar","Wifey Material","Treat Her Right"]', 'https://via.placeholder.com/300?text=Abizzy', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Dallas Baimba', 'Dallas B', 'Hip-Hop', 'Makeni', 'Sierra Leone', 'Makeni-born rapper with motivational lyrics and hard-hitting beats.', '["Rise Up","Level","No Time"]', 'https://via.placeholder.com/300?text=Dallas+B', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Xzu-B Turay', 'Xzu-B', 'Hip-Hop', 'Freetown', 'Sierra Leone', 'Versatile rapper fusing krio slang with contemporary hip-hop.', '["Borku Sense","Loma","Warrior"]', 'https://via.placeholder.com/300?text=Xzu-B', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Hero Blaq Kamara', 'Hero Blaq', 'Afropop', 'Bo', 'Sierra Leone', 'Melodic Afropop artist crafting uplifting tunes for the dancefloor.', '["Cool Me Down","Special","Holiday"]', 'https://via.placeholder.com/300?text=Hero+Blaq', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Michael Conteh', 'M.I.C', 'Hip-Hop', 'Freetown', 'Sierra Leone', 'Storytelling emcee highlighting everyday Salone life with sharp bars.', '["Parliament","On God","Blessings"]', 'https://via.placeholder.com/300?text=MIC', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Ibrahim Turay', 'I-Tribe', 'Afropop', 'Kenema', 'Sierra Leone', 'Kenema-born singer known for romantic Afropop and soaring hooks.', '["Sengbe","Level Up","Darling"]', 'https://via.placeholder.com/300?text=I-Tribe', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Joel Dennis', 'Jooel', 'Afro-fusion', 'Freetown', 'Sierra Leone', 'Genre-blending vocalist with soulful tones and electronic edges.', '["Fire Dey","Angelina","Enjoyment"]', 'https://via.placeholder.com/300?text=Jooel', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Jacob Evangelista', 'The Therapist', 'Afrobeats', 'Freetown', 'Sierra Leone', 'Breakout Afrobeats act who went viral with dance-ready singles.', '["Nack","Move It","Monica"]', 'https://via.placeholder.com/300?text=The+Therapist', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Melvin George', 'Mello Seven', 'Afro-fusion', 'Kenema', 'Sierra Leone', 'Rising Afro-fusion artist weaving heartfelt lyrics with soft melodies.', '["Comfort","Tonight","Energy"]', 'https://via.placeholder.com/300?text=Mello+Seven', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Nasser Ayoub', '7even R', 'Afropop', 'Freetown', 'Sierra Leone', 'Pop-forward performer known for uplifting hooks and wide appeal.', '["Onyah","Follow Me","Turn Up"]', 'https://via.placeholder.com/300?text=7even+R', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Fantacee Koroma', 'Fantacee Wiz', 'Folk', 'Kono', 'Sierra Leone', 'Folk storyteller preserving tradition with modern acoustic flair.', '["Yagba","Rise","Home"]', 'https://via.placeholder.com/300?text=Fantacee+Wiz', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Patricia Pratt', 'Empress Pee', 'Gospel', 'Freetown', 'Sierra Leone', 'Gospel voice delivering soulful praise and inspirational anthems.', '["Bless Me","Hallelujah","My King"]', 'https://via.placeholder.com/300?text=Empress+Pee', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Joseph Cole', 'Daddy Saj', 'Hip-Hop', 'Freetown', 'Sierra Leone', 'Pioneer of conscious hip-hop with bold commentary on society.', '["Corruption E Do So","Cheer Up","Pride"]', 'https://via.placeholder.com/300?text=Daddy+Saj', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Joseph Lamin Deen', 'Pupa Bajah', 'Reggae', 'Freetown', 'Sierra Leone', 'Frontman of Bajah and the Dry Eye Crew blending reggae and hip-hop.', '["Any Side We Dae","Gun Thing","Peace Na Weapon"]', 'https://via.placeholder.com/300?text=Pupa+Bajah', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Mohamed Kuti', 'Innocent Kuti', 'Reggae/Dancehall', 'Freetown', 'Sierra Leone', 'Roots-driven artist with conscious reggae and dancehall fusion.', '["Believe","Jah Guide","Higher"]', 'https://via.placeholder.com/300?text=Innocent+Kuti', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Collins Archer', 'Colabo', 'Afropop', 'Bo', 'Sierra Leone', 'Afropop singer celebrated for catchy hooks and collaborative spirit.', '["Happy Time","Fine Girl","No Worry"]', 'https://via.placeholder.com/300?text=Colabo', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('LXG Collective', 'LXG', 'Afropop', 'Freetown', 'Sierra Leone', 'Hit-making collective delivering club-ready anthems and hooks.', '["La Wena","Slow Wine","Only You"]', 'https://via.placeholder.com/300?text=LXG', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Future Kanu', 'Future K', 'Dancehall', 'Freetown', 'Sierra Leone', 'Dancehall artist blending patois energy with krio flavor.', '["Kill Dem","Rude Bwoy","Gyal Flex"]', 'https://via.placeholder.com/300?text=Future+K', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Fynface Sesay', 'Fynface', 'R&B', 'Freetown', 'Sierra Leone', 'Smooth R&B vocalist with romantic ballads and soulful runs.', '["For You","Sweet Love","Stay"]', 'https://via.placeholder.com/300?text=Fynface', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Felicia Kanneh', 'Lady Felicia', 'Gospel', 'Bo', 'Sierra Leone', 'Beloved gospel artist inspiring listeners with powerful worship.', '["No One Like You","Grateful","Lift Him"]', 'https://via.placeholder.com/300?text=Lady+Felicia', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Isatta Sheriff', 'Isatta Sheriff', 'Hip-Hop', 'Freetown', 'Sierra Leone', 'UK-based Salone rapper blending conscious bars with jazz influences.', '["Aviatrix","Everything","Give Me a Minute"]', 'https://via.placeholder.com/300?text=Isatta+Sheriff', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Mariama Jalloh', 'Mariama', 'Folk/Pop', 'Kenema', 'Sierra Leone', 'Singer-songwriter with gentle folk-pop storytelling and acoustic vibes.', '["Easy Way Out","Oh My My","Raindrops"]', 'https://via.placeholder.com/300?text=Mariama', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Natasha Beckley', 'Swadu', 'Afropop', 'Makeni', 'Sierra Leone', 'Former beauty queen turned Afropop artist celebrating Salone pride.', '["Money","Gimme Love","Hold My Hand"]', 'https://via.placeholder.com/300?text=Natasha+Beckley', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Yasmine Gbondo', 'Yasmine', 'Afropop', 'Freetown', 'Sierra Leone', 'Singer with bright Afropop melodies and smooth mid-tempo grooves.', '["Desire","Closer","Glow"]', 'https://via.placeholder.com/300?text=Yasmine', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Ibrahim Koroma', 'Prezo Koroma', 'Hip-Hop', 'Koidu', 'Sierra Leone', 'Hard-spitting rapper bringing Kono stories to national stages.', '["Hustle","Motive","Numbers"]', 'https://via.placeholder.com/300?text=Prezo+Koroma', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Mansaray Sheku', 'Mash P', 'Afropop', 'Bo', 'Sierra Leone', 'Afropop vocalist delivering bright hooks and dance-ready choruses.', '["Kam Join Me","Bounce","Faya"]', 'https://via.placeholder.com/300?text=Mash+P', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Christian Bolt', 'C-Bolt', 'Hip-Hop', 'Kenema', 'Sierra Leone', 'Hip-hop artist known for rapid-fire delivery and motivational bars.', '["Charged Up","Pressure","Goal"]', 'https://via.placeholder.com/300?text=C-Bolt', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Mohamed Bangura', 'Oracle', 'Afro-soul', 'Freetown', 'Sierra Leone', 'Soulful crooner merging Afro-soul with R&B textures.', '["Light","Heal","Distance"]', 'https://via.placeholder.com/300?text=Oracle', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Fatmata Conteh', 'Suga Lulu', 'Afropop', 'Freetown', 'Sierra Leone', 'Sweet-toned singer with playful Afropop and dance vibes.', '["Sugar Rush","Hold Tight","Luku Me"]', 'https://via.placeholder.com/300?text=Suga+Lulu', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Neneh Aisha', 'Queennak', 'Afropop', 'Freetown', 'Sierra Leone', 'Fashion-forward Afropop artist blending pop hooks with cultural pride.', '["Bongo","Come Closer","Ride"]', 'https://via.placeholder.com/300?text=Queennak', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Nelly Kabba', 'Nelly Kabba', 'Afropop', 'Freetown', 'Sierra Leone', 'Singer and actress delivering catchy Afropop and feel-good tunes.', '["Oluwa","Carry Go","Smile"]', 'https://via.placeholder.com/300?text=Nelly+Kabba', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Hassan Kamara', 'King Harman', 'Afrobeat', 'Makeni', 'Sierra Leone', 'Afrobeat act mixing northern rhythms with modern percussion.', '["Mariya","One Time","Gonga"]', 'https://via.placeholder.com/300?text=King+Harman', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Rolka Mansaray', 'Empress Rolka', 'Dancehall', 'Kenema', 'Sierra Leone', 'Dancehall artist with bold patois delivery and energetic shows.', '["Bad Gyal","Program","Link Up"]', 'https://via.placeholder.com/300?text=Empress+Rolka', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Abdulai Timbo', 'Timbo', 'Afrobeats', 'Port Loko', 'Sierra Leone', 'Afrobeats singer bringing Port Loko flavor to the mainstream.', '["Lifestyle","Body","Waka"]', 'https://via.placeholder.com/300?text=Timbo', 'https://youtube.com', '', 'https://instagram.com', 'https://facebook.com', NOW(), NOW()),
('Judah Zubairu', 'Judah Zubairu', 'Gospel', 'Freetown', 'Sierra Leone', 'Gospel recording artist and worship minister.', '["Yahweh Reigns","Overflow"]', 'https://via.placeholder.com/300?text=Judah+Zubairu', 'https://youtube.com/@JudahZubairu', '', 'https://instagram.com/judahzubairu', '', NOW(), NOW()),
('Melford Vincent', 'Melford Vincent', 'Gospel', 'Freetown', 'Sierra Leone', 'Gospel worship leader associated with Flood Worship.', '["Flood of Mercy","Holy Fire"]', 'https://via.placeholder.com/300?text=Melford+Vincent', 'https://youtube.com/@MelfordVincent', '', 'https://instagram.com/melfordvincent', '', NOW(), NOW()),
('Melinda Tucker', 'Melinda Tucker', 'Gospel', 'Freetown', 'Sierra Leone', 'Upcoming gospel singer and songwriter.', '["New Song","Ever Near"]', 'https://via.placeholder.com/300?text=Melinda+Tucker', 'https://youtube.com/@MelindaTucker', '', 'https://instagram.com/melindatucker', '', NOW(), NOW()),
('Arnold Fofana', 'Arnold Fofana', 'Gospel', 'Freetown', 'Sierra Leone', 'Gospel worshipper, preacher, and vocal coach.', '["You Are Holy","For My Good"]', 'https://via.placeholder.com/300?text=Arnold+Fofana', 'https://youtube.com/@ArnoldFofana', '', 'https://instagram.com/arnoldfofana', '', NOW(), NOW()),
('Fire Twins', 'Fire Twins', 'Gospel', 'Freetown', 'Sierra Leone', 'Sierra Leone gospel duo bringing energetic worship music.', '["Fire Come Down","Praise Anthem"]', 'https://via.placeholder.com/300?text=Fire+Twins', 'https://youtube.com/@FireTwins', '', 'https://instagram.com/firetwins', '', NOW(), NOW()),
('Barak Choir', 'Barak Choir', 'Gospel', 'Freetown', 'Sierra Leone', 'Inter-denominational gospel choir known for powerful live ministrations.', '["Halleluyah Praise","Arise and Shine"]', 'https://via.placeholder.com/300?text=Barak+Choir', 'https://youtube.com/@BarakChoir', '', 'https://instagram.com/barakchoir', '', NOW(), NOW()),
('Min Delight Konneh', 'Min Delight Konneh', 'Gospel', 'Freetown', 'Sierra Leone', 'Gospel minister noted for collaborations such as with Mercy Ships.', '["Anchor of Hope","Mercy Ship"]', 'https://via.placeholder.com/300?text=Delight+Konneh', 'https://youtube.com/@DelightKonneh', '', 'https://instagram.com/delightkonneh', '', NOW(), NOW()),
('Khadison Duwai', 'Khadison Duwai', 'Gospel', 'Freetown', 'Sierra Leone', 'Gospel artist dedicated to worship and inspirational music.', '["Breath of God","I Surrender"]', 'https://via.placeholder.com/300?text=Khadison+Duwai', 'https://youtube.com/@KhadisonDuwai', '', 'https://instagram.com/khadisonduwai', '', NOW(), NOW());

